version: '3.1'

services:
  mysql:
    container_name: mysql-demo-atenea
    image: mysql:8.0.23
    command: mysqld --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=atenea
      - MYSQL_PASSWORD=atenea
      - MYSQL_DATABASE=atenea-db
    ports:
      - 3306:3306
volumes:
  mysql-demo-atenea:
